# Generated by Django 5.2.5 on 2026-02-14 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_userprofile_avatar_hire_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Partner"),
                    ("MANAGER", "Administrador"),
                    ("SALES_REP", "Asociado"),
                ],
                default="SALES_REP",
                max_length=20,
            ),
        ),
    ]
