# Generated by Django 5.2.5 on 2026-03-05 01:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_roles_and_backfill_profiles(apps, schema_editor):
    Role = apps.get_model("core", "Role")
    UserProfile = apps.get_model("core", "UserProfile")

    hierarchy = [
        ("PARTNER", "Partner", 1),
        ("ADMINISTRATOR", "Administrador", 2),
        ("JR_PARTNER", "Jr Partner", 3),
        ("BUSINESS_MANAGER", "Business Manager", 4),
        ("ELITE_MANAGER", "Elite Manager", 5),
        ("SENIOR_MANAGER", "Senior Manager", 6),
        ("MANAGER", "Manager", 7),
        ("SOLAR_ADVISOR", "Solar Advisor", 8),
        ("SOLAR_CONSULTANT", "Solar Consultant", 9),
    ]

    role_map = {}
    parent = None
    for code, name, priority in hierarchy:
        role, _ = Role.objects.get_or_create(
            code=code,
            defaults={
                "name": name,
                "priority": priority,
                "parent": parent,
                "is_active": True,
            },
        )
        updates = []
        if role.name != name:
            role.name = name
            updates.append("name")
        if role.priority != priority:
            role.priority = priority
            updates.append("priority")
        if role.parent_id != (parent.id if parent else None):
            role.parent = parent
            updates.append("parent")
        if updates:
            role.save(update_fields=updates)
        role_map[code] = role
        parent = role

    legacy_map = {
        "ADMIN": "PARTNER",
        "MANAGER": "MANAGER",
        "SALES_REP": "SOLAR_CONSULTANT",
    }

    for profile in UserProfile.objects.select_related("user").all():
        role_code = legacy_map.get(profile.role, profile.role)
        if role_code not in role_map:
            role_code = "PARTNER" if profile.user.is_superuser else "SOLAR_CONSULTANT"
        profile.role = role_code
        profile.role_ref_id = role_map[role_code].id
        profile.save(update_fields=["role", "role_ref"])


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_userprofile_business_units"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userprofile",
            options={"ordering": ["user__username"]},
        ),
        migrations.AddField(
            model_name="userprofile",
            name="manager",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="managed_profiles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[
                    ("PARTNER", "Partner"),
                    ("ADMINISTRATOR", "Administrador"),
                    ("JR_PARTNER", "Jr Partner"),
                    ("BUSINESS_MANAGER", "Business Manager"),
                    ("ELITE_MANAGER", "Elite Manager"),
                    ("SENIOR_MANAGER", "Senior Manager"),
                    ("MANAGER", "Manager"),
                    ("SOLAR_ADVISOR", "Solar Advisor"),
                    ("SOLAR_CONSULTANT", "Solar Consultant"),
                ],
                default="SOLAR_CONSULTANT",
                max_length=40,
            ),
        ),
        migrations.CreateModel(
            name="ModulePermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "module",
                    models.CharField(
                        choices=[
                            ("users", "Usuarios"),
                            ("sales", "Ventas"),
                            ("reports", "Reportes"),
                            ("settings", "Configuracion"),
                            ("commissions", "Comisiones"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("view", "Ver"),
                            ("manage", "Gestionar"),
                            ("approve", "Aprobar"),
                        ],
                        max_length=40,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["module", "action"],
                "unique_together": {("module", "action")},
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("PARTNER", "Partner"),
                            ("ADMINISTRATOR", "Administrador"),
                            ("JR_PARTNER", "Jr Partner"),
                            ("BUSINESS_MANAGER", "Business Manager"),
                            ("ELITE_MANAGER", "Elite Manager"),
                            ("SENIOR_MANAGER", "Senior Manager"),
                            ("MANAGER", "Manager"),
                            ("SOLAR_ADVISOR", "Solar Advisor"),
                            ("SOLAR_CONSULTANT", "Solar Consultant"),
                        ],
                        max_length=40,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("priority", models.PositiveSmallIntegerField(db_index=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="children",
                        to="core.role",
                    ),
                ),
            ],
            options={
                "ordering": ["priority", "id"],
            },
        ),
        migrations.AddField(
            model_name="userprofile",
            name="role_ref",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="profiles",
                to="core.role",
            ),
        ),
        migrations.RunPython(seed_roles_and_backfill_profiles, migrations.RunPython.noop),
        migrations.CreateModel(
            name="RoleChangeAudit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "previous_role",
                    models.CharField(
                        choices=[
                            ("PARTNER", "Partner"),
                            ("ADMINISTRATOR", "Administrador"),
                            ("JR_PARTNER", "Jr Partner"),
                            ("BUSINESS_MANAGER", "Business Manager"),
                            ("ELITE_MANAGER", "Elite Manager"),
                            ("SENIOR_MANAGER", "Senior Manager"),
                            ("MANAGER", "Manager"),
                            ("SOLAR_ADVISOR", "Solar Advisor"),
                            ("SOLAR_CONSULTANT", "Solar Consultant"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "new_role",
                    models.CharField(
                        choices=[
                            ("PARTNER", "Partner"),
                            ("ADMINISTRATOR", "Administrador"),
                            ("JR_PARTNER", "Jr Partner"),
                            ("BUSINESS_MANAGER", "Business Manager"),
                            ("ELITE_MANAGER", "Elite Manager"),
                            ("SENIOR_MANAGER", "Senior Manager"),
                            ("MANAGER", "Manager"),
                            ("SOLAR_ADVISOR", "Solar Advisor"),
                            ("SOLAR_CONSULTANT", "Solar Consultant"),
                        ],
                        max_length=40,
                    ),
                ),
                ("reason", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="role_changes_performed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_changes_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="RoleModulePermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("allowed", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "permission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_permissions",
                        to="core.modulepermission",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="module_permissions",
                        to="core.role",
                    ),
                ),
            ],
            options={
                "ordering": [
                    "role__priority",
                    "permission__module",
                    "permission__action",
                ],
                "unique_together": {("role", "permission")},
            },
        ),
    ]
