# Generated by Django 5.2.5 on 2026-03-05 01:15

from django.db import migrations, models


def normalize_role_codes_and_priority(apps, schema_editor):
    Role = apps.get_model("core", "Role")
    UserProfile = apps.get_model("core", "UserProfile")
    RoleChangeAudit = apps.get_model("core", "RoleChangeAudit")

    old_code = "ADMINISTRATOR"
    new_code = "ADMINISTRADOR"

    old_role = Role.objects.filter(code=old_code).first()
    new_role = Role.objects.filter(code=new_code).first()

    if old_role and not new_role:
        old_role.code = new_code
        old_role.name = "Administrador"
        old_role.save(update_fields=["code", "name"])
        new_role = old_role
    elif old_role and new_role:
        UserProfile.objects.filter(role=old_code).update(role=new_code, role_ref_id=new_role.id)
        RoleChangeAudit.objects.filter(previous_role=old_code).update(previous_role=new_code)
        RoleChangeAudit.objects.filter(new_role=old_code).update(new_role=new_code)
        old_role.delete()

    UserProfile.objects.filter(role=old_code).update(role=new_code)
    RoleChangeAudit.objects.filter(previous_role=old_code).update(previous_role=new_code)
    RoleChangeAudit.objects.filter(new_role=old_code).update(new_role=new_code)

    hierarchy = [
        ("PARTNER", "Partner", 100),
        ("ADMINISTRADOR", "Administrador", 90),
        ("JR_PARTNER", "Jr Partner", 85),
        ("BUSINESS_MANAGER", "Business Manager", 80),
        ("ELITE_MANAGER", "Elite Manager", 70),
        ("SENIOR_MANAGER", "Senior Manager", 60),
        ("MANAGER", "Manager", 50),
        ("SOLAR_ADVISOR", "Solar Advisor", 40),
        ("SOLAR_CONSULTANT", "Solar Consultant", 30),
    ]

    role_map = {}
    parent = None
    for code, name, priority in hierarchy:
        role, _ = Role.objects.get_or_create(
            code=code,
            defaults={
                "name": name,
                "priority": priority,
                "parent": parent,
                "is_active": True,
            },
        )
        updates = []
        if role.name != name:
            role.name = name
            updates.append("name")
        if role.priority != priority:
            role.priority = priority
            updates.append("priority")
        if role.parent_id != (parent.id if parent else None):
            role.parent = parent
            updates.append("parent")
        if updates:
            role.save(update_fields=updates)
        role_map[code] = role
        parent = role

    for profile in UserProfile.objects.all():
        role = role_map.get(profile.role)
        if role:
            profile.role_ref_id = role.id
            profile.save(update_fields=["role_ref"])


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_userprofile_options_userprofile_manager_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="role",
            name="code",
            field=models.CharField(
                choices=[
                    ("PARTNER", "Partner"),
                    ("ADMINISTRADOR", "Administrador"),
                    ("JR_PARTNER", "Jr Partner"),
                    ("BUSINESS_MANAGER", "Business Manager"),
                    ("ELITE_MANAGER", "Elite Manager"),
                    ("SENIOR_MANAGER", "Senior Manager"),
                    ("MANAGER", "Manager"),
                    ("SOLAR_ADVISOR", "Solar Advisor"),
                    ("SOLAR_CONSULTANT", "Solar Consultant"),
                ],
                max_length=40,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="rolechangeaudit",
            name="new_role",
            field=models.CharField(
                choices=[
                    ("PARTNER", "Partner"),
                    ("ADMINISTRADOR", "Administrador"),
                    ("JR_PARTNER", "Jr Partner"),
                    ("BUSINESS_MANAGER", "Business Manager"),
                    ("ELITE_MANAGER", "Elite Manager"),
                    ("SENIOR_MANAGER", "Senior Manager"),
                    ("MANAGER", "Manager"),
                    ("SOLAR_ADVISOR", "Solar Advisor"),
                    ("SOLAR_CONSULTANT", "Solar Consultant"),
                ],
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="rolechangeaudit",
            name="previous_role",
            field=models.CharField(
                choices=[
                    ("PARTNER", "Partner"),
                    ("ADMINISTRADOR", "Administrador"),
                    ("JR_PARTNER", "Jr Partner"),
                    ("BUSINESS_MANAGER", "Business Manager"),
                    ("ELITE_MANAGER", "Elite Manager"),
                    ("SENIOR_MANAGER", "Senior Manager"),
                    ("MANAGER", "Manager"),
                    ("SOLAR_ADVISOR", "Solar Advisor"),
                    ("SOLAR_CONSULTANT", "Solar Consultant"),
                ],
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[
                    ("PARTNER", "Partner"),
                    ("ADMINISTRADOR", "Administrador"),
                    ("JR_PARTNER", "Jr Partner"),
                    ("BUSINESS_MANAGER", "Business Manager"),
                    ("ELITE_MANAGER", "Elite Manager"),
                    ("SENIOR_MANAGER", "Senior Manager"),
                    ("MANAGER", "Manager"),
                    ("SOLAR_ADVISOR", "Solar Advisor"),
                    ("SOLAR_CONSULTANT", "Solar Consultant"),
                ],
                default="SOLAR_CONSULTANT",
                max_length=40,
            ),
        ),
        migrations.RunPython(normalize_role_codes_and_priority, migrations.RunPython.noop),
    ]
