# Generated by Django 5.2.12 on 2026-03-06 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0009_repair_salesreplevel_schema"),
        ("finance", "0002_financingpartner"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommissionAllocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role_code", models.CharField(blank=True, max_length=40)),
                ("share_percent", models.DecimalField(decimal_places=4, max_digits=6)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("calculated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "commission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allocations",
                        to="finance.commission",
                    ),
                ),
                (
                    "sale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commission_allocations",
                        to="crm.sale",
                    ),
                ),
                (
                    "sales_rep",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commission_allocations",
                        to="crm.salesrep",
                    ),
                ),
            ],
            options={
                "ordering": ["-calculated_at", "id"],
                "unique_together": {("commission", "sales_rep")},
            },
        ),
    ]
