from django.urls import path, re_path

from dashboard import views

app_name = "dashboard"

urlpatterns = [
    re_path(r"^mi-equipo/(?P<raw_url>https?://.+)$", views.redirect_nested_absolute_url, name="redirect_nested_absolute_url"),
    path("", views.home, name="home"),
    path("admin-overview/", views.admin_overview, name="admin_overview"),
    path("solar/", views.business_unit_overview, {"unit_key": "solar"}, name="unit_solar"),
    path("solar/cotizador/", views.quoter_iframe, name="quoter_iframe"),
    path("solar/sunrun/", views.sunrun_iframe, name="sunrun_iframe"),
    path("solar/email/", views.email_iframe, name="email_iframe"),
    path("solar/residencial/", views.solar_residential_iframe, name="solar_residential"),
    path("solar/comercial/", views.solar_commercial_iframe, name="solar_commercial"),
    path("solar/cliente-residencial/", views.solar_client_residential_iframe, name="solar_client_residential"),
    path("solar/venta-residencial/", views.solar_sale_residential_iframe, name="solar_sale_residential"),
    path("solar/cliente-comercial/", views.solar_client_commercial_iframe, name="solar_client_commercial"),
    path("solar/venta-comercial/", views.solar_sale_commercial_iframe, name="solar_sale_commercial"),
    path("techo/", views.business_unit_overview, {"unit_key": "techo"}, name="unit_techo"),
    path("sunvida/", views.business_unit_overview, {"unit_key": "sunvida"}, name="unit_sunvida"),
    path("cash-d/", views.business_unit_overview, {"unit_key": "cash-d"}, name="unit_cash_d"),
    path("agua/", views.business_unit_overview, {"unit_key": "agua"}, name="unit_agua"),
    path("internet/", views.business_unit_overview, {"unit_key": "internet"}, name="unit_internet"),
    path("sales-overview/", views.sales_overview, name="sales_overview"),
    path("sales/", views.sales_list, name="sales_list"),
    path("sales/<int:pk>/", views.sales_detail, name="sales_detail"),
    path("mi-perfil/", views.associate_profile, name="associate_profile"),
    path("points/", views.points_summary, name="points_summary"),
    path("call-logs/", views.call_logs, name="call_logs"),
    path("call-logs/new/", views.call_log_create, name="call_log_create"),
    path("financiamiento/", views.financing, name="financing"),
    path("accesos/", views.access_management, name="access_management"),
    path("gestion-clientes/", views.client_management, name="client_management"),
    path("informacion-asociados/", views.associates_info, name="associates_info"),
    path("apps/crm/salesteam/", views.apps_crm_sales_team_view, name="apps_crm_sales_team_view"),
    path("apps/crm/salesteam-graph", views.apps_crm_salesteam_graph, name="apps_crm_salesteam_graph"),
    path("apps/crm/salesteam-graph-source", views.apps_crm_salesteam_graph_source, name="apps_crm_salesteam_graph_source"),
    path("apps/crm/salesteam-personal/", views.apps_crm_sales_team_personal_info_view, name="apps_crm_sales_team_personal_info_view"),
    path("apps/api/salesrep_profile/", views.salesrep_profile_api, name="salesrep_profile_api"),
    path("apps/crm/salesteam/admin-role/<int:salesrep_id>/", views.apps_crm_salesteam_admin_role, name="apps_crm_salesteam_admin_role"),
    path("apps/crm/salesteam/admin-invite/<int:request_id>/action/", views.apps_crm_salesteam_admin_invite_action, name="apps_crm_salesteam_admin_invite_action"),
    path("apps/salesrep-promotion/create/<int:salesrep_id>", views.salesrep_promotion_modal, name="salesrep_promotion_modal"),
    path("apps/salesrep-promotion/removal/create/<int:salesrep_id>/", views.salesrep_removal_modal, name="salesrep_removal_modal"),
    path("jerarquia-ventas/", views.sales_hierarchy, name="sales_hierarchy"),
    path("estructura-comisiones/", views.commission_structure, name="commission_structure"),
    path("crece-tu-equipo/", views.grow_team, name="grow_team"),
    path("registro-invitacion/<str:signed_token>/", views.invitation_register, name="invitation_register"),
    path(
        "pages/authentication/signup-invited/<int:parent_id>/<int:level_id>/",
        views.CustomSignupView.as_view(),
        name="signup_invited",
    ),
    path(
        "authentication/signup-invited/<int:parent_id>/<int:level_id>/",
        views.CustomSignupView.as_view(),
        name="signup_invited_alias",
    ),
    path("cambios-de-nivel/", views.level_changes, name="level_changes"),
    path("mi-equipo/", views.my_team, name="my_team"),
    path("mi-equipo/data/", views.my_team_data_api, name="my_team_data_api"),
    path("tareas/", views.tasks, name="tasks"),
    path("tareas/feed/", views.tasks_calendar_feed, name="tasks_calendar_feed"),
    path("tareas/task/<int:pk>/status/", views.task_update_status, name="task_update_status"),
    path("tareas/cita/<int:pk>/status/", views.appointment_update_status, name="appointment_update_status"),
    path("herramientas/", views.tools, name="tools"),
    path("herramientas/recurso/<int:pk>/", views.tools_resource_present, name="tools_resource_present"),
    path("legales/", views.legal, name="legal"),
    path("ayuda/", views.help_center, name="help_center"),
]
