# Generated by Django 5.2.5 on 2026-02-14 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_userprofile_business_units"),
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="business_units",
            field=models.ManyToManyField(
                blank=True, related_name="appointments", to="core.businessunit"
            ),
        ),
        migrations.AddField(
            model_name="calendarevent",
            name="business_units",
            field=models.ManyToManyField(
                blank=True, related_name="calendar_events", to="core.businessunit"
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="business_units",
            field=models.ManyToManyField(
                blank=True, related_name="tasks", to="core.businessunit"
            ),
        ),
    ]
