# Generated by Django 5.2.5 on 2026-02-14 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0003_sharedresource"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResourceTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="sharedresource",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="sharedresource",
            name="provider",
            field=models.CharField(blank=True, default="Interno", max_length=120),
        ),
        migrations.AddField(
            model_name="sharedresource",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="resources", to="dashboard.resourcetag"
            ),
        ),
    ]
