# Generated by Django 5.2.5 on 2026-02-14 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0005_announcement"),
    ]

    operations = [
        migrations.AddField(
            model_name="announcement",
            name="media_file",
            field=models.FileField(blank=True, null=True, upload_to="announcements/"),
        ),
        migrations.AddField(
            model_name="announcement",
            name="media_type",
            field=models.CharField(
                choices=[
                    ("none", "Sin medio"),
                    ("pdf", "PDF"),
                    ("video", "Video"),
                    ("image", "Imagen"),
                ],
                default="none",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="announcement",
            name="video_url",
            field=models.URLField(blank=True),
        ),
    ]
