# Generated by Django 5.2.5 on 2026-02-14 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_userprofile_business_units"),
        ("dashboard", "0007_offer"),
    ]

    operations = [
        migrations.AddField(
            model_name="offer",
            name="business_units",
            field=models.ManyToManyField(
                blank=True, related_name="offers", to="core.businessunit"
            ),
        ),
    ]
