# Generated by Django 5.2.11 on 2026-02-13 22:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesrep',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='associates/avatars/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])]),
        ),
    ]
