# Generated by Django 5.2.11 on 2026-02-13 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_salesrep_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesrep',
            name='physical_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='salesrep',
            name='postal_address',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
