# Generated by Django 5.2.11 on 2026-02-13 23:28

import django.core.validators
from django.db import migrations, models


def migrate_legacy_addresses(apps, schema_editor):
    SalesRep = apps.get_model("crm", "SalesRep")
    for rep in SalesRep.objects.all().iterator():
        old_postal = (getattr(rep, "postal_address", "") or "").strip()
        old_physical = (getattr(rep, "physical_address", "") or "").strip()

        if old_postal and not rep.postal_address_line_1:
            rep.postal_address_line_1 = old_postal[:120]
        if old_physical and not rep.physical_address_line_1:
            rep.physical_address_line_1 = old_physical[:120]

        if old_postal and old_physical and old_postal == old_physical:
            rep.physical_same_as_postal = True

        rep.save(
            update_fields=[
                "postal_address_line_1",
                "physical_address_line_1",
                "physical_same_as_postal",
            ]
        )


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0004_salesrep_physical_address_salesrep_postal_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesrep",
            name="physical_address_line_1",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="salesrep",
            name="physical_address_line_2",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="salesrep",
            name="physical_city",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="salesrep",
            name="physical_same_as_postal",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="salesrep",
            name="physical_state",
            field=models.CharField(
                blank=True,
                choices=[
                    ("AL", "Alabama"),
                    ("AK", "Alaska"),
                    ("AZ", "Arizona"),
                    ("AR", "Arkansas"),
                    ("CA", "California"),
                    ("CO", "Colorado"),
                    ("CT", "Connecticut"),
                    ("DE", "Delaware"),
                    ("FL", "Florida"),
                    ("GA", "Georgia"),
                    ("HI", "Hawaii"),
                    ("ID", "Idaho"),
                    ("IL", "Illinois"),
                    ("IN", "Indiana"),
                    ("IA", "Iowa"),
                    ("KS", "Kansas"),
                    ("KY", "Kentucky"),
                    ("LA", "Louisiana"),
                    ("ME", "Maine"),
                    ("MD", "Maryland"),
                    ("MA", "Massachusetts"),
                    ("MI", "Michigan"),
                    ("MN", "Minnesota"),
                    ("MS", "Mississippi"),
                    ("MO", "Missouri"),
                    ("MT", "Montana"),
                    ("NE", "Nebraska"),
                    ("NV", "Nevada"),
                    ("NH", "New Hampshire"),
                    ("NJ", "New Jersey"),
                    ("NM", "New Mexico"),
                    ("NY", "New York"),
                    ("NC", "North Carolina"),
                    ("ND", "North Dakota"),
                    ("OH", "Ohio"),
                    ("OK", "Oklahoma"),
                    ("OR", "Oregon"),
                    ("PA", "Pennsylvania"),
                    ("RI", "Rhode Island"),
                    ("SC", "South Carolina"),
                    ("SD", "South Dakota"),
                    ("TN", "Tennessee"),
                    ("TX", "Texas"),
                    ("UT", "Utah"),
                    ("VT", "Vermont"),
                    ("VA", "Virginia"),
                    ("WA", "Washington"),
                    ("WV", "West Virginia"),
                    ("WI", "Wisconsin"),
                    ("WY", "Wyoming"),
                    ("DC", "District of Columbia"),
                    ("PR", "Puerto Rico"),
                ],
                max_length=2,
            ),
        ),
        migrations.AddField(
            model_name="salesrep",
            name="physical_zip_code",
            field=models.CharField(
                blank=True,
                max_length=10,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Use ZIP en formato 12345 o 12345-6789.", regex="^\\d{5}(-\\d{4})?$"
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="salesrep",
            name="postal_address_line_1",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="salesrep",
            name="postal_address_line_2",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="salesrep",
            name="postal_city",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="salesrep",
            name="postal_state",
            field=models.CharField(
                blank=True,
                choices=[
                    ("AL", "Alabama"),
                    ("AK", "Alaska"),
                    ("AZ", "Arizona"),
                    ("AR", "Arkansas"),
                    ("CA", "California"),
                    ("CO", "Colorado"),
                    ("CT", "Connecticut"),
                    ("DE", "Delaware"),
                    ("FL", "Florida"),
                    ("GA", "Georgia"),
                    ("HI", "Hawaii"),
                    ("ID", "Idaho"),
                    ("IL", "Illinois"),
                    ("IN", "Indiana"),
                    ("IA", "Iowa"),
                    ("KS", "Kansas"),
                    ("KY", "Kentucky"),
                    ("LA", "Louisiana"),
                    ("ME", "Maine"),
                    ("MD", "Maryland"),
                    ("MA", "Massachusetts"),
                    ("MI", "Michigan"),
                    ("MN", "Minnesota"),
                    ("MS", "Mississippi"),
                    ("MO", "Missouri"),
                    ("MT", "Montana"),
                    ("NE", "Nebraska"),
                    ("NV", "Nevada"),
                    ("NH", "New Hampshire"),
                    ("NJ", "New Jersey"),
                    ("NM", "New Mexico"),
                    ("NY", "New York"),
                    ("NC", "North Carolina"),
                    ("ND", "North Dakota"),
                    ("OH", "Ohio"),
                    ("OK", "Oklahoma"),
                    ("OR", "Oregon"),
                    ("PA", "Pennsylvania"),
                    ("RI", "Rhode Island"),
                    ("SC", "South Carolina"),
                    ("SD", "South Dakota"),
                    ("TN", "Tennessee"),
                    ("TX", "Texas"),
                    ("UT", "Utah"),
                    ("VT", "Vermont"),
                    ("VA", "Virginia"),
                    ("WA", "Washington"),
                    ("WV", "West Virginia"),
                    ("WI", "Wisconsin"),
                    ("WY", "Wyoming"),
                    ("DC", "District of Columbia"),
                    ("PR", "Puerto Rico"),
                ],
                max_length=2,
            ),
        ),
        migrations.AddField(
            model_name="salesrep",
            name="postal_zip_code",
            field=models.CharField(
                blank=True,
                max_length=10,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Use ZIP en formato 12345 o 12345-6789.", regex="^\\d{5}(-\\d{4})?$"
                    )
                ],
            ),
        ),
        migrations.RunPython(migrate_legacy_addresses, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="salesrep",
            name="physical_address",
        ),
        migrations.RemoveField(
            model_name="salesrep",
            name="postal_address",
        ),
    ]
