# Generated by Django 5.2.11 on 2026-02-13 23:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_remove_salesrep_physical_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesrep',
            name='second_last_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='salesrep',
            name='phone',
            field=models.CharField(blank=True, max_length=13, validators=[django.core.validators.RegexValidator(message='Use teléfono en formato (XXX)XXX-XXXX.', regex='^\\(\\d{3}\\)\\d{3}-\\d{4}$')]),
        ),
    ]
