# Generated by Django 5.2.12 on 2026-03-05 19:32

import crm.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_role_code_alter_rolechangeaudit_new_role_and_more"),
        ("crm", "0006_salesrep_second_last_name_alter_salesrep_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesrep",
            name="consultant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="advisor_profiles",
                to="crm.salesrep",
            ),
        ),
        migrations.AddField(
            model_name="salesrep",
            name="consultant_rate",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name="salesrep",
            name="executivemanager",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="business_manager_profiles",
                to="crm.salesrep",
            ),
        ),
        migrations.AddField(
            model_name="salesrep",
            name="executivemanager_rate",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name="salesrep",
            name="jr_partner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="jr_partner_profiles",
                to="crm.salesrep",
            ),
        ),
        migrations.AddField(
            model_name="salesrep",
            name="jr_partner_rate",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name="salesrep",
            name="level",
            field=models.ForeignKey(
                default=crm.models.get_default_salesrep_level_id,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sales_reps",
                to="core.role",
            ),
        ),
        migrations.AddField(
            model_name="salesrep",
            name="manager",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="senior_manager_profiles",
                to="crm.salesrep",
            ),
        ),
        migrations.AddField(
            model_name="salesrep",
            name="manager_rate",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name="salesrep",
            name="modified_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="salesrep",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children_profiles",
                to="crm.salesrep",
            ),
        ),
        migrations.AddField(
            model_name="salesrep",
            name="parent_rate",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name="salesrep",
            name="partner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="partner_profiles",
                to="crm.salesrep",
            ),
        ),
        migrations.AddField(
            model_name="salesrep",
            name="partner_rate",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name="salesrep",
            name="promanager",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="elite_manager_profiles",
                to="crm.salesrep",
            ),
        ),
        migrations.AddField(
            model_name="salesrep",
            name="promanager_rate",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name="salesrep",
            name="sunrun_account_flag",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="salesrep",
            name="teamleader",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="manager_profiles",
                to="crm.salesrep",
            ),
        ),
        migrations.AddField(
            model_name="salesrep",
            name="teamleader_rate",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name="salesrep",
            name="trainee_rate",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name="salesrep",
            name="zoho_id",
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
