# Generated by Django 5.2.12 on 2026-03-05 20:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0007_salesrep_consultant_salesrep_consultant_rate_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SalesrepLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                ("sales_goal", models.PositiveIntegerField(default=0)),
                (
                    "indirect_sales_cap_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("sort_value", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["id"],
            },
        ),
    ]
