# Generated by Django 5.2.12 on 2026-03-07 23:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0009_repair_salesreplevel_schema"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="acceptance_deadline",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="lead",
            name="account_number",
            field=models.CharField(blank=True, db_index=True, max_length=80),
        ),
        migrations.AddField(
            model_name="lead",
            name="address",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="lead",
            name="assigned_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lead",
            name="assigned_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_leads",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="city",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="lead",
            name="consumo_promedio_kwh",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="duplicate_blocked",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="lead",
            name="electricity_bill",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="invoice_hash",
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name="lead",
            name="invoice_name",
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name="lead",
            name="invoice_pdf",
            field=models.FileField(blank=True, null=True, upload_to="leads/invoices/"),
        ),
        migrations.AddField(
            model_name="lead",
            name="is_accepted",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name="lead",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=7, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="lead_kind",
            field=models.CharField(
                choices=[("residential", "Residencial"), ("commercial", "Comercial")],
                db_index=True,
                default="residential",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="location_id",
            field=models.CharField(blank=True, db_index=True, max_length=80),
        ),
        migrations.AddField(
            model_name="lead",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=7, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="message",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="lead",
            name="meter_number",
            field=models.CharField(blank=True, db_index=True, max_length=80),
        ),
        migrations.AddField(
            model_name="lead",
            name="monthly_consumption_history",
            field=models.TextField(blank=True, default="[]"),
        ),
        migrations.AddField(
            model_name="lead",
            name="owner_name",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="lead",
            name="roof_type",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="lead",
            name="status",
            field=models.CharField(
                choices=[
                    ("NEW", "Nuevo"),
                    ("PENDING", "Pendiente"),
                    ("CONTACTED", "Contactado"),
                    ("QUALIFIED", "Calificado"),
                    ("CLOSED", "Cerrado"),
                ],
                db_index=True,
                default="NEW",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="system_size_kw",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="lead",
            name="work_deadline",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="InvoiceDuplicateOverride",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "account_number",
                    models.CharField(blank=True, db_index=True, max_length=80),
                ),
                (
                    "meter_number",
                    models.CharField(blank=True, db_index=True, max_length=80),
                ),
                (
                    "location_id",
                    models.CharField(blank=True, db_index=True, max_length=80),
                ),
                (
                    "invoice_hash",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("expires_at", models.DateTimeField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "requester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoice_duplicate_overrides",
                        to="crm.salesrep",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "db_table": "crm_invoice_duplicate_override_v2",
            },
        ),
        migrations.CreateModel(
            name="InvoiceDuplicateReviewRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pendiente"),
                            ("APPROVED", "Aprobada"),
                            ("REJECTED", "Rechazada"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("reason", models.TextField(blank=True)),
                ("resolver_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="duplicate_review_requests",
                        to="crm.lead",
                    ),
                ),
                (
                    "requester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="duplicate_review_requests",
                        to="crm.salesrep",
                    ),
                ),
                (
                    "resolver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_duplicate_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "db_table": "crm_invoice_duplicate_review_request_v2",
            },
        ),
        migrations.CreateModel(
            name="LeadActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("VIEW", "Ver detalle"),
                            ("PHONE", "Llamada"),
                            ("EMAIL", "Correo"),
                            ("SMS", "SMS"),
                            ("WHATSAPP", "WhatsApp"),
                            ("ASSIGN", "Asignacion"),
                            ("ACCEPT", "Aceptacion"),
                        ],
                        max_length=24,
                    ),
                ),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lead_activity_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_logs",
                        to="crm.lead",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "db_table": "crm_lead_activity_log_v2",
            },
        ),
        migrations.CreateModel(
            name="LeadNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("body", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lead_notes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="crm.lead",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "db_table": "crm_lead_note_v2",
            },
        ),
    ]
