# Generated by Django 5.2.12 on 2026-03-08 00:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0010_lead_acceptance_deadline_lead_account_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoiceduplicateoverride",
            name="used_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="invoiceduplicateoverride",
            name="used_on_lead",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="consumed_overrides",
                to="crm.lead",
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="account_occupation_luma",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="lead",
            name="battery_option",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="lead",
            name="customer_address",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="lead",
            name="customer_city",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="lead",
            name="customer_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="lead",
            name="customer_latitude",
            field=models.DecimalField(
                blank=True, decimal_places=7, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="customer_longitude",
            field=models.DecimalField(
                blank=True, decimal_places=7, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="customer_name",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="lead",
            name="customer_phone",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="lead",
            name="customer_phone2",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="lead",
            name="eff",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="electricity_invoice_language",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name="lead",
            name="electricity_invoice_page1_img",
            field=models.ImageField(blank=True, null=True, upload_to="leads/invoices/"),
        ),
        migrations.AddField(
            model_name="lead",
            name="electricity_invoice_page2_img",
            field=models.ImageField(blank=True, null=True, upload_to="leads/invoices/"),
        ),
        migrations.AddField(
            model_name="lead",
            name="electricity_invoice_pdf",
            field=models.FileField(blank=True, null=True, upload_to="leads/invoices/"),
        ),
        migrations.AddField(
            model_name="lead",
            name="financing",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="lead",
            name="hsp",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="id_consumo_historial",
            field=models.TextField(blank=True, default="[]"),
        ),
        migrations.AddField(
            model_name="lead",
            name="last_4_ssn_luma",
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name="lead",
            name="lead_source",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="lead",
            name="loan_reference_number",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="lead",
            name="marital_status",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name="lead",
            name="offset",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="other_documents",
            field=models.FileField(blank=True, null=True, upload_to="leads/documents/"),
        ),
        migrations.AddField(
            model_name="lead",
            name="owns_property",
            field=models.CharField(
                blank=True, choices=[("SI", "SI"), ("NO", "NO")], max_length=5
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="password_luma",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="lead",
            name="proof_title",
            field=models.FileField(blank=True, null=True, upload_to="leads/documents/"),
        ),
        migrations.AddField(
            model_name="lead",
            name="sunrun_call_completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="lead",
            name="sunrun_contract_signed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="lead",
            name="system_size",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="total_project_cost",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="use_invoice_images",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="lead",
            name="username_luma",
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
