# Generated by Django 5.2.12 on 2026-03-08 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0011_invoiceduplicateoverride_used_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="electricity_invoice_hash",
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name="lead",
            name="electricity_invoice_page3_img",
            field=models.ImageField(blank=True, null=True, upload_to="leads/invoices/"),
        ),
        migrations.AddField(
            model_name="lead",
            name="electricity_invoice_page4_img",
            field=models.ImageField(blank=True, null=True, upload_to="leads/invoices/"),
        ),
    ]
