# Generated by Django 5.2.12 on 2026-03-08 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0012_lead_electricity_invoice_hash_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="customer_country",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="lead",
            name="customer_postal_code",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="lead",
            name="status",
            field=models.CharField(
                choices=[
                    ("Nuevo", "Nuevo"),
                    ("Contactado", "Contactado"),
                    ("Calificado", "Calificado"),
                    ("Descalificado", "Descalificado"),
                    ("Propuesta Enviada", "Propuesta Enviada"),
                    ("En Negociación", "En Negociación"),
                    ("Vendido", "Vendido"),
                    ("Perdido", "Perdido"),
                    ("NEW", "Nuevo (legacy)"),
                    ("PENDING", "Pendiente (legacy)"),
                    ("CONTACTED", "Contactado (legacy)"),
                    ("QUALIFIED", "Calificado (legacy)"),
                    ("CLOSED", "Cerrado (legacy)"),
                ],
                db_index=True,
                default="Nuevo",
                max_length=20,
            ),
        ),
    ]
