# Generated by Django 5.2.12 on 2026-03-08 16:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0014_leadsource"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CrmDeal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deal_kind",
                    models.CharField(
                        choices=[
                            ("residential", "Residencial"),
                            ("commercial", "Comercial"),
                            ("portable_battery", "Portable Battery"),
                            ("autos", "Autos"),
                        ],
                        db_index=True,
                        default="residential",
                        max_length=40,
                    ),
                ),
                (
                    "imported_salesrep_name",
                    models.CharField(blank=True, max_length=180),
                ),
                ("imported_at", models.DateTimeField(blank=True, null=True)),
                ("customer_name", models.CharField(blank=True, max_length=160)),
                ("customer_phone", models.CharField(blank=True, max_length=30)),
                ("customer_email", models.EmailField(blank=True, max_length=254)),
                ("customer_city", models.CharField(blank=True, max_length=80)),
                ("customer_address", models.CharField(blank=True, max_length=200)),
                (
                    "proposal_id",
                    models.CharField(blank=True, db_index=True, max_length=120),
                ),
                (
                    "sunrun_service_contract_id",
                    models.CharField(blank=True, db_index=True, max_length=120),
                ),
                (
                    "system_size",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=12, null=True
                    ),
                ),
                (
                    "epc_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "epc_base",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "epc_table",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "epc_adjustment",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("planned", "Planificado"),
                            ("approved", "Aprobado"),
                            ("signed", "Firmado"),
                            ("installed", "Instalado"),
                            ("closed", "Cerrado"),
                        ],
                        db_index=True,
                        default="planned",
                        max_length=40,
                    ),
                ),
                (
                    "closing_date",
                    models.DateField(blank=True, db_index=True, null=True),
                ),
                ("sr_signoff_date", models.DateField(blank=True, null=True)),
                ("customer_sign_off_date", models.DateField(blank=True, null=True)),
                ("final_completion_date", models.DateField(blank=True, null=True)),
                ("consultant_name", models.CharField(blank=True, max_length=160)),
                ("advisor_name", models.CharField(blank=True, max_length=160)),
                ("manager_name", models.CharField(blank=True, max_length=160)),
                ("senior_manager_name", models.CharField(blank=True, max_length=160)),
                ("elite_manager_name", models.CharField(blank=True, max_length=160)),
                ("business_manager_name", models.CharField(blank=True, max_length=160)),
                ("jr_partner_name", models.CharField(blank=True, max_length=160)),
                ("partner_name", models.CharField(blank=True, max_length=160)),
                (
                    "consultant_rate",
                    models.DecimalField(decimal_places=4, default=0, max_digits=7),
                ),
                (
                    "advisor_rate",
                    models.DecimalField(decimal_places=4, default=0, max_digits=7),
                ),
                (
                    "manager_rate",
                    models.DecimalField(decimal_places=4, default=0, max_digits=7),
                ),
                (
                    "senior_manager_rate",
                    models.DecimalField(decimal_places=4, default=0, max_digits=7),
                ),
                (
                    "elite_manager_rate",
                    models.DecimalField(decimal_places=4, default=0, max_digits=7),
                ),
                (
                    "business_manager_rate",
                    models.DecimalField(decimal_places=4, default=0, max_digits=7),
                ),
                (
                    "jr_partner_rate",
                    models.DecimalField(decimal_places=4, default=0, max_digits=7),
                ),
                (
                    "partner_rate",
                    models.DecimalField(decimal_places=4, default=0, max_digits=7),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "imported_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="imported_crm_deals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "salesrep",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="crm_deals",
                        to="crm.salesrep",
                    ),
                ),
            ],
            options={
                "ordering": ["-closing_date", "-id"],
                "permissions": (("can_reassign_deal", "Can reassign deals"),),
            },
        ),
    ]
